nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}
